// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emelxiyaeyjmrjvwlarj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtZWx4aXlhZXlqbXJqdndsYXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMDExMzcsImV4cCI6MjA1ODU3NzEzN30.C7FgHCXzWVIRLNe0sYbml-M29_IhAjTatA26Ibdk5Tc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);